### PR TITLE
Add yaml templates - remove dependency on toml gem

### PR DESCRIPTION
**Pull request by zoojar**

### CODE REVIEW

**Comment by zoojar** [comment]
> hi @zoojar , thanks for the PR! Do you have some links to the telegraf docs that mention the yaml format? I didn't know that's supported and I didn't find it in the docs.

no worries! I can't see anywhere where telegraf supports yaml. BUT, this is to remove the dependency on the toml gem - the templates are only used as hashes to pass to the telegraf input defined type!

**Comment by MartyEwings** [comment]
Iv resolved some issues with the CI if anyone would like to try this one again

**Comment by zoojar** [comment]
> Iv resolved some issues with the CI if anyone would like to try this one again

thank you. I'm not sure it's working - failing on setup

**Comment by MartyEwings** [comment]
@zoojar i had to pin a gem,  you probably need to rebase to suck it in

**Comment by zoojar** [comment]
> @zoojar i had to pin a gem, you probably need to rebase to suck it in

cheers, now done, but failing on one os: https://github.com/puppetlabs/puppet_operational_dashboards/actions/runs/12029742951/job/33535840586?pr=219

**Comment by MartyEwings** [comment]
@zoojar i think thats a grafana/sles incompatibility rather than an issue

**Comment by zoojar** [comment]
> @zoojar i had to pin a gem, you probably need to rebase to suck it in

after the rebase. failing on the same checks that ran with #222

**Comment by MartyEwings** [comment]
@zoojar Sles i think has an a compatibility issue for a while dont sweat it, iv got some due diligence to do then ill merge

**Review by MartyEwings — APPROVED** [review]

**Pull request merged**
