### PR TITLE
(SUP-3565) Support Telegraf archive install on EL

### PR DESCRIPTION
**Pull request by m0dular**
This commit adds support for installing Telegraf from an archive source
on Enterprise Linux variants.

### CODE REVIEW

**Comment by m0dular** [comment]
This uses [my fork](https://github.com/voxpupuli/puppet-telegraf/pull/190) of `puppet-telegraf` in the fixtures so the tests can run.  Please do not merge yet, as we'll need to change that back after the PR is merged.

**Comment by m0dular** [comment]
Waiting on a new release of puppet/telegraf, then we can kick this.

**Comment by jarretlavallee** [comment]
If this requires a specific version of the module, we should update the lower end of it in the metadata.json.

**Comment by MartyEwings** [comment]
Kicking the testing

**Review by tuxmea — APPROVED** [review]

**Comment by m0dular** [comment]
The current status is that we need a metadata bump for this change https://github.com/puppetlabs/influxdb/pull/50

Also, adding `manage_archive` changed the logic a bit and makes it want to use an archive install by default on Ubuntu.  I'll have a fix for these in a bit.

**Review by MartyEwings — COMMENTED** [review]
This looks good to me now @m0dular you happy to merge?

**Pull request merged**
