### PR TITLE
Collect system metrics via telegraf

### PR DESCRIPTION
**Pull request by bastelfreak**

### CODE REVIEW

**Comment by m0dular** [comment]
Would this collect system metrics from Puppet infra nodes, or just the dashboard node itself?  I haven't tested it yet, but at a glance it looks like it only adds a Telegraf input to the dashboard node to collect its local `sar` metrics.

 I think this also hits on something we've been trying to figure out with this module, which is what should be included for customers vs what should be included for Support.  We did add [Charlie's sar script](https://github.com/puppetlabs/puppet_operational_dashboards/blob/main/files/plan_files/sar2influx.rb) that can import `sa` files and populate the v2 System Metrics dashboard.  This is great for us because most people have `sar` collection turned on and we collect them in a support script, but not useful for customers because the module doesn't automate it other than offering the `load_metrics` plan.  I'm sure there's _some_ way to collect `sar` metrics from remote nodes using the tools we have, but I don't know what the best way for this module to do it is.

One option might be to use the code from the [import script](https://github.com/puppetlabs/puppet_operational_dashboards/blob/50bcc5c91a086c194a0ddcc724c55f7f551fc591/files/plan_files/import_archives.sh#L41-L50) to parse and ship local `sar` metrics to a remote InfluxDB.  There could be a new profile class that you apply to Puppet infra nodes that does something like:

* Ensure `sar` is installed and collecting metrics
* Create a Telegraf output that points to our InfluxDB server
* Configure an `exec` Telegraf input plugin that runs the script similar to [here](https://github.com/puppetlabs/puppet_operational_dashboards/blob/main/files/plan_files/system_sar.conf)

In general, we should make a decision on if this is a good solution for getting system metrics and if it should live in the module or somewhere else.  I did consider splitting out the plans and scripts we use internally into another repo, but didn't decide on anything yet.

**Comment by bastelfreak** [comment]
@m0dular thanks for the feedback. I think the module should be split. the plans and the system dashboard aren't used outside of the PE support team I think? And it's confusing for people that there's an empty dashboard (it's good that this is now configureable).

I cleaned up the telegraf config and dropped the diskio and sysstat inputs, they aren't used by the dashboard. At the moment the dashboard and the inputs aren't configured by default. people that deploy everything on a single node can set `collect_system_metrics` and `manage_telegraf_system_dashboard` to true in the main class or set `collect_system_metrics` to true in the agent::telegraf subclass. The class already configures an output so I only add additional inputs.

I prefer telegraf over the sar implementation because why shouldn't we use the native telegraf plugins? I had a longer conversation with David Sandilands about metrics and I think it's important to understand how and if a system is utilized. That only works when system- and puppet-specific metrices are combined.

**Comment by MartyEwings** [comment]
@m0dular can you have a look at the most recent updates

**Comment by m0dular** [comment]
I tested this out, but I'm still unsure of what the desired behavior is.  If the goal is to collect system metrics from PE infra nodes, this won't accomplish that because it only collects the new metrics from the dashboard node itself.  If we want these metrics from PE nodes, we'd have to either create a new profile class or modify `puppet_operational_dashboards::telegraf::agent` like in my previous comment and apply that to said nodes.

**Pull request closed without merging**
